### ISSUE TITLE
Rewrite conclusion episode

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/good-enough-practices#24]
The conclusion section is not very coherent in its current form, and would I think be better if shorter.

Probably:
* include links to other resources, e.g. ten simple rules for computational research as link
* remove the "funders recommendations" and other parts of the "good enough practices paper that don't directly pertain to learners
* add discussion for "most important thing you learned today"?

**Comment by FlicAnderson** [comment]
Agreed during #32  that the "What We Left Out" section is rather intimidating and includes a lot of rather detailed and specific information, which probably doesn't belong in a conclusions/summary section. 

We should remove this section, and instead point confident learners towards the ["Best Practices in Scientific Computing"](https://doi.org/10.1371/journal.pbio.1001745) paper to allow them to learn more and build on the foundational skills from Good Enough Practices from this workshop content.

**Comment by FlicAnderson** [comment]
"Ten simple rules" section could be re-formatted to remove title capitalisation and improve legibility.

**Comment by FlicAnderson** [comment]
Could potentially frame part of the conclusions section in terms of advice to different levels of users (for example students and early-stage researchers; post-docs and lab/support staff or mid-stage researchers; experienced; PIs). @ewallace thought this might be helpful?

This could include recommendations to support colleagues to adopt some of these measures as this will help improve the overall level of the research group, as well as making colleagues better collaborators, and thus improving life for the learner themselves as a result! :)

**Comment by FlicAnderson** [comment]
@DimmestP, @ewallace and I have agreed that the conclusions episode needs to be renamed.  No other Carpentries workshops have 'conclusions' episodes, and the Carpentries workshop development handbook defines an episode as:  
> Each episode teaches a set of related concepts (for example, navigating files and directories or indexing and subsetting data). It lists measurable learning objectives related to those concepts and contains a number of challenges to assess learners’ ability to perform those learning objectives.  

Since the conclusions episode does not currently include measurable learning objectives and might be a repetition of earlier key points and objectives, it might not necessarily reach this bar. 

@ewallace has proposed renaming the episode to "What's Next?" and will update the episode with key points to include and signposting to further resources. 

It's worth considering how this final episode teaches in alpha workshops, as it might be worthwhile adding this content to an 'instructor notes - finishing the workshop' section rather than teaching as an episode? However, this can be informed by testing 'in the wild' and getting feedback from the instructor and attendees on how this format teaches.
