### ISSUE TITLE
Suggestion to include an example of a 'quick editing process' for collaborative manuscripts

### ISSUE THREAD

**Issue by FlicAnderson** [carpentries-incubator/good-enough-practices#62]
A collaborator to the riboviz project suggested that creating an example of how a 'quick collaborative git manuscript workflow' might look would be really useful, and would fit into the  `07-manuscripts.md` lesson.

This would feature collaborators e.g. Agnes and Bob and describe the branch, edit, add/commit/push, pull request, review, merge process.

**Comment by ewallace** [comment]
I like this idea. But, it is addressed in the carpentries git lesson.

I'm also not sure because in my experience of teaching the lesson mostly to first year PhD students, we almost never get to the manuscripts episode.

What about we address it by linking to the git lesson for an example of a collaborative workflow?
